apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rainbow
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rainbow
        visualize: "true"
        version: v1
    spec:
      containers:
      - name: rainbow
        image: abderrazak/rainbow:health
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10 # default is 10s
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: rainbow-service
  labels:
    app: rainbow
    visualize: "true"
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: rainbow

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rainbow
spec:
  backend:
    serviceName: rainbow-service
    servicePort: 3000