apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rainbow-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: rainbow-nginx
    spec:
      containers:
      - name: rainbow-nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: rainbow-nginx
  labels:
    run: rainbow-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: rainbow-nginx